const PASS_STUDIO_BASE_URL="https://www.passstudio.online/api/v1";const REQUEST_TIMEOUT_MS=10000;const DEFAULT_PASS_STUDIO_PASS_ID="kBQ15unyR1QPeUhcRWID";
export type PassStudioPass={passId:string;name:string;passType?:string;status?:string;distributionMode?:string;fieldsEditable?:boolean;fieldKeys?:string[];templateOwnedFieldKeys?:string[]};
export type PassStudioIssueResult={instanceId:string;passstudioHolderId:string;barcodeContent:string;shareToken?:string;addToWalletUrl:string;emailSent?:boolean;alreadyExisted?:boolean};export type PassStudioInstanceUpdateResult={ok:boolean;instanceId:string;updatedFields:string[];pushed:boolean;warnings?:unknown[]};export type PassStudioNotificationMessage=string|Record<string,string>;export type ResolvePassStudioPassOptions={passId?:string|null;passName?:string|null;allowSoleActiveFallback?:boolean};
export class PassStudioError extends Error{readonly status:number;readonly code:string;constructor(status:number,code:string){super(code);this.name="PassStudioError";this.status=status;this.code=code;}}
function safeCode(v:unknown){const t=String(v??"PASS_STUDIO_UNAVAILABLE").toUpperCase().replace(/[^A-Z0-9_:-]/g,"_").slice(0,96);return t||"PASS_STUDIO_UNAVAILABLE"}function normalizePassName(v:string|null|undefined){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase().replace(/[^a-z0-9]/g,"")}
async function request<T>(apiKey:string,path:string,init:RequestInit={}):Promise<T>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(`${PASS_STUDIO_BASE_URL}${path}`,{...init,signal:controller.signal,headers:{Authorization:`Bearer ${apiKey}`,Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers??{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new PassStudioError(response.status,safeCode(payload?.code??`PASS_STUDIO_HTTP_${response.status}`));return payload as T}catch(error){if(error instanceof PassStudioError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new PassStudioError(504,"PASS_STUDIO_TIMEOUT");throw new PassStudioError(502,"PASS_STUDIO_UNAVAILABLE")}finally{clearTimeout(timeout)}}
export function requirePassStudioApiKey(){const k=(Deno.env.get("PASS_STUDIO_API_KEY")??"").trim();if(!k)throw new PassStudioError(503,"PASS_STUDIO_NOT_CONFIGURED");return k}export async function listPassStudioPasses(apiKey:string){const p=await request<{passes?:PassStudioPass[]}>(apiKey,"/passes?limit=200");return Array.isArray(p.passes)?p.passes:[]}
export async function resolvePassStudioPass(apiKey:string,options:ResolvePassStudioPassOptions={}):Promise<PassStudioPass>{const hasId=Object.prototype.hasOwnProperty.call(options,"passId"),hasName=Object.prototype.hasOwnProperty.call(options,"passName");const configuredId=String(hasId?options.passId??"":Deno.env.get("PASS_STUDIO_PASS_ID")??DEFAULT_PASS_STUDIO_PASS_ID).trim(),configuredName=String(hasName?options.passName??"":Deno.env.get("PASS_STUDIO_PASS_NAME")??"Chargeurs+").trim(),passes=await listPassStudioPasses(apiKey),byId=configuredId?passes.find(p=>p.passId===configuredId):undefined,n=normalizePassName(configuredName),byName=n?passes.find(p=>normalizePassName(p.name)===n):undefined,active=passes.filter(p=>String(p.status??"active").toLowerCase()==="active"),only=options.allowSoleActiveFallback===false?undefined:active.length===1?active[0]:undefined,match=byId??byName??only;if(!match)throw new PassStudioError(503,configuredId||configuredName?"PASS_STUDIO_PASS_ID_OR_NAME_NOT_FOUND":"PASS_STUDIO_PASS_NOT_FOUND");if(String(match.status??"active").toLowerCase()!=="active")throw new PassStudioError(409,"PASS_STUDIO_PASS_NOT_ACTIVE");return match}
function editableFields(pass:PassStudioPass,fields:Record<string,string|number|boolean|null>){const e=new Set(pass.fieldKeys??[]),t=new Set(pass.templateOwnedFieldKeys??[]);return Object.fromEntries(Object.entries(fields).filter(([k])=>e.has(k)&&!t.has(k)))}
export async function issuePassStudioPass(apiKey:string,pass:PassStudioPass,input:{email:string;name?:string|null;phone?:string|null;fields:Record<string,string|number|boolean|null>}):Promise<PassStudioIssueResult>{return await request(apiKey,`/passes/${encodeURIComponent(pass.passId)}/issue`,{method:"POST",body:JSON.stringify({email:input.email,...(input.name?{name:input.name}:{}),...(input.phone?{phone:input.phone}:{}),sendEmail:false,resendIfExists:false,fields:editableFields(pass,input.fields)})})}
export async function updatePassStudioInstance(apiKey:string,pass:PassStudioPass,instanceId:string,fields:Record<string,string|number|boolean|null>,message?:PassStudioNotificationMessage|null):Promise<PassStudioInstanceUpdateResult>{return await request(apiKey,"/instances/fields",{method:"PATCH",body:JSON.stringify({instanceId,fields:editableFields(pass,fields),...(message?{message}:{})})})}

