import Stripe from "https://esm.sh/stripe@17.7.0?target=deno";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
import { computeFinalPricingFromSnapshot, type FrozenReturnState } from "../_shared/pricingSnapshot.ts";
import { shouldReverseMembershipCreditReservation, stripeAmountAfterMembershipCredit } from "../_shared/membershipCreditReservation.ts";

const STRIPE_API_VERSION = "2025-09-30.clover" as any;
const LOCK_TTL_MINUTES = 10;
const headers = { ...corsHeaders, "Content-Type": "application/json" };
const db = () => createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, { auth: { persistSession: false } });
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers });

type ReturnState = FrozenReturnState;
type Session = Record<string, any>;
type Strategy = "manual_capture" | "prepaid_refund";

function safeEqual(a: string, b: string) { if (!a || !b || a.length !== b.length) return false; let m = 0; for (let i = 0; i < a.length; i++) m |= a.charCodeAt(i) ^ b.charCodeAt(i); return m === 0; }
function authorized(req: Request) { return safeEqual(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "", (req.headers.get("Authorization") ?? "").replace(/^Bearer\s+/i, "")); }
function cents(v: unknown) { const n = Math.round(Number(v ?? 0)); if (!Number.isFinite(n) || n < 0) throw new Error("INVALID_AMOUNT"); return n; }
function canonicalize(v: unknown): string { if (v === null || typeof v !== "object") return JSON.stringify(v); if (Array.isArray(v)) return `[${v.map(canonicalize).join(",")}]`; const o = v as Record<string, unknown>; return `{${Object.keys(o).sort().map(k => `${JSON.stringify(k)}:${canonicalize(o[k])}`).join(",")}}`; }
async function snapshotHash(v: unknown) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonicalize(v))); return Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, "0")).join(""); }
function cleanError(e: any) { const clean = (v: unknown, max = 300) => typeof v === "string" ? v.replace(/(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+/g, "[REDACTED_KEY]").replace(/whsec_[A-Za-z0-9]+/g, "[REDACTED_WEBHOOK_SECRET]").slice(0, max) : null; return { type: clean(e?.type, 80), code: clean(e?.code, 120), decline_code: clean(e?.decline_code, 120), param: clean(e?.param, 120), request_id: clean(e?.requestId, 120), message: clean(e?.message, 320) }; }
function errorCode(e: any) { if (typeof e?.code === "string" && e.code) return `${typeof e?.type === "string" && e.type.startsWith("Stripe") ? "STRIPE" : "DB"}_${e.code.toUpperCase()}`.slice(0, 120); if (typeof e?.message === "string" && /^[A-Z0-9_:-]+$/.test(e.message)) return e.message.slice(0, 120); return typeof e?.name === "string" ? e.name : "UNKNOWN_ERROR"; }
async function audit(client: any, action: string, target: string, data: Record<string, unknown>) { try { await client.from("audit_logs").insert({ action, target, data }); } catch {} }
async function logApi(client: any, entry: Record<string, unknown>) { try { await client.from("api_logs").insert(entry); } catch {} }
async function incident(client: any, s: Session, code: string, message: string, details: Record<string, unknown> = {}) { try { await client.from("system_incidents").insert({ type: "payment_settlement", severity: code === "SUPPLEMENTAL_PAYMENT_REQUIRED" ? "warning" : "high", message, data: { rental_session_id: s.id, station_id: s.station_id, code, ...details }, resolved: false }); } catch {} await audit(client, "settlement.incident.opened", String(s.id), { code, ...details }); }
async function fail(client: any, s: Session, code: string, message: string, details: Record<string, unknown> = {}) { await client.from("rental_sessions").update({ settlement_status: "failed", settlement_error: code, settlement_locked_at: null, failure_code: code, failure_message: message }).eq("id", s.id); await incident(client, s, code, message, { retryable: true, ...details }); }
async function orchState(client: any, id: string) { const { data, error } = await client.from("rental_orchestrator_snapshots").select("state,version").eq("rental_id", id).maybeSingle(); if (error) throw error; return data; }
async function appendEvent(client: any, s: Session, type: string, resultingState: string, key: string, metadata: Record<string, unknown>, finalChf: number | null = null) {
  for (let i = 0; i < 3; i++) {
    const snap = await orchState(client, String(s.id)); if (!snap) throw new Error("ORCHESTRATOR_SNAPSHOT_MISSING");
    if (String(snap.state) === resultingState) return;
    const { data: existing } = await client.from("rental_orchestrator_events").select("event_type").eq("rental_id", s.id).eq("idempotency_key", key).maybeSingle(); if (existing) return;
    const { error } = await client.rpc("append_rental_orchestrator_event", { p_rental_id: s.id, p_expected_version: Number(snap.version ?? 0), p_event_type: type, p_idempotency_key: key, p_occurred_at: new Date().toISOString(), p_metadata: metadata, p_resulting_state: resultingState, p_payment_intent_id: s.stripe_payment_intent_id ?? null, p_station_id: s.station_id ?? null, p_battery_id: s.battery_id ?? null, p_final_amount_chf: finalChf, p_failure_reason: null });
    if (!error) return; if (String(error.message ?? "").includes("VERSION_CONFLICT") || error.code === "40001") continue; if (String(error.message ?? "").includes("IDEMPOTENCY_KEY_CONFLICT")) return; throw error;
  }
  throw new Error("VERSION_CONFLICT");
}
async function claim(client: any, id: string): Promise<Session | null> { const { data, error } = await client.rpc("claim_rental_settlement", { p_rental_id: id, p_lock_ttl_minutes: LOCK_TTL_MINUTES }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; if (!row || typeof row.id !== "string" || !row.id) return null; return row as Session; }
async function paymentMethodType(stripe: Stripe, intent: Stripe.PaymentIntent) { const id = typeof intent.payment_method === "string" ? intent.payment_method : intent.payment_method?.id; if (id) try { const pm = await stripe.paymentMethods.retrieve(id); if (pm.type) return pm.type; } catch {} return intent.payment_method_types?.[0] ?? "unknown"; }
function cardCapture(intent: Stripe.PaymentIntent) { const v = (intent.payment_method_options as any)?.card?.capture_method; return typeof v === "string" ? v : null; }
function strategy(s: Session, intent: Stripe.PaymentIntent, method: string): Strategy { if (s.settlement_strategy === "manual_capture" || s.settlement_strategy === "prepaid_refund") return s.settlement_strategy; if (method === "card" && intent.status === "requires_capture" && cents(intent.amount_capturable) > 0) return "manual_capture"; if (method === "card" && cardCapture(intent) === "manual") return "manual_capture"; return method === "card" && intent.capture_method === "manual" ? "manual_capture" : "prepaid_refund"; }
function plan(strategy: Strategy, finalCents: number, deposit: number, capturable: number, captured: number, alreadyRefunded: number) { if (strategy === "manual_capture") { const capture = Math.min(finalCents, capturable); return { capture, cancel: capture === 0 && capturable > 0, refund: 0, supplemental: Math.max(0, finalCents - capture) }; } const refundable = Math.max(0, captured - alreadyRefunded); return { capture: 0, cancel: false, refund: Math.min(Math.max(0, captured - finalCents), refundable), supplemental: Math.max(0, finalCents - captured) }; }
function amountDetails(amount: number) { return { enforce_arithmetic_validation: true, line_items: [{ product_name: "Chargeurs.ch location", product_code: "RENTAL", quantity: 1, unit_cost: amount }] }; }
async function reserveMembershipRentalCredit(client: any, rentalId: string, reservationCapCents: number, minimumCreditCents: number) {
  const { data, error } = await client.rpc("apply_customer_membership_credit_to_rental", { p_rental_id: rentalId, p_reservation_cap_cents: reservationCapCents, p_minimum_credit_cents: minimumCreditCents });
  if (error) throw error;
  const row = Array.isArray(data) ? data[0] : data;
  const reserved = cents(row?.applied_cents ?? 0);
  if (row?.currency && String(row.currency).toUpperCase() !== "CHF") throw new Error("MEMBERSHIP_CREDIT_CURRENCY_UNSUPPORTED");
  return { reserved, requirementMet: row?.requirement_met === true };
}
async function commitMembershipRentalCredit(client: any, rentalId: string, finalAmountCents: number) {
  const { data, error } = await client.rpc("commit_customer_membership_credit_for_rental", { p_rental_id: rentalId, p_final_amount_cents: finalAmountCents });
  if (error) throw error;
  return cents(data ?? 0);
}
async function reverseMembershipRentalCredit(client: any, rentalId: string, reason: string) {
  const { error } = await client.rpc("reverse_customer_membership_credit_for_rental", { p_rental_id: rentalId, p_reason: reason });
  if (error) throw error;
}
async function markMembershipCreditForReconciliation(client: any, rentalId: string) {
  const { error } = await client.from("rental_sessions").update({ membership_credit_reservation_status: "reconciliation_required" }).eq("id", rentalId);
  if (error) throw error;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json({ ok: false, error: "METHOD_NOT_ALLOWED" }, 405);
  if (!authorized(req)) return json({ ok: false, error: "FORBIDDEN" }, 403);
  const client = db(); let rentalId = ""; let membershipCreditReservedCents = 0; let stripeSideEffectStarted = false; let membershipCreditCommitted = false;
  try {
    const body = await req.json().catch(() => ({})); rentalId = typeof body.rentalSessionId === "string" ? body.rentalSessionId : ""; if (!rentalId) return json({ ok: false, error: "MISSING_SESSION" }, 400);
    const returnState: ReturnState = body.returnState === "not_returned" ? "not_returned" : "normal"; const finalAt = typeof body.finalAt === "string" && Number.isFinite(Date.parse(body.finalAt)) ? body.finalAt : new Date().toISOString();
    const { data: existing, error: readError } = await client.from("rental_sessions").select("*").eq("id", rentalId).maybeSingle(); if (readError) throw readError; if (!existing) return json({ ok: false, error: "SESSION_NOT_FOUND" }, 404); if (existing.settlement_status === "settled") return json({ ok: true, idempotent: true, settlement_status: "settled", final_amount_cents: existing.final_amount_cents });
    if (existing.settlement_strategy === "membership_prepaid") return json({ ok: false, error: "MEMBERSHIP_PREPAID_SETTLEMENT_PENDING", settlement_status: existing.settlement_status ?? null }, 409);
    const secret = (Deno.env.get("STRIPE_SECRET_KEY") ?? "").trim(), mode = (Deno.env.get("STRIPE_MODE") ?? "").trim().toLowerCase(), liveEnabled = (Deno.env.get("STRIPE_LIVE_ENABLED") ?? "").trim().toLowerCase();
    if (mode !== "test" || liveEnabled !== "false" || !(secret.startsWith("sk_test_") || secret.startsWith("rk_test_"))) return json({ ok: false, error: "STRIPE_TEST_MODE_REQUIRED" }, 503);
    const s = await claim(client, rentalId); if (!s) return json({ ok: true, already_in_progress: true }, 202);
    const snapshot = s.pricing_snapshot as Record<string, unknown> | null, hash = typeof s.pricing_snapshot_hash === "string" ? s.pricing_snapshot_hash : ""; if (!snapshot || !hash) { await fail(client, s, "PRICING_SNAPSHOT_MISSING", "Le snapshot tarifaire immuable de la location est absent."); return json({ ok: false, error: "PRICING_SNAPSHOT_MISSING" }, 409); } if (await snapshotHash(snapshot) !== hash) { await fail(client, s, "PRICING_SNAPSHOT_HASH_MISMATCH", "Le snapshot tarifaire de la location ne correspond plus à son empreinte d'origine."); return json({ ok: false, error: "PRICING_SNAPSHOT_HASH_MISMATCH" }, 409); }
    const start = s.started_at ?? s.ejected_at ?? s.created_at, end = returnState === "normal" ? s.returned_at ?? finalAt : finalAt; const p = computeFinalPricingFromSnapshot({ snapshot, expectedCurrency: String(s.currency ?? "CHF"), startAt: start, endAt: end, returnState }), finalCents = cents(p.final_cents), deposit = cents(s.deposit_amount_cents ?? snapshot.deposit_cents ?? 0), pi = String(s.stripe_payment_intent_id ?? ""); if (!pi) { await fail(client, s, "PAYMENT_INTENT_MISSING", "Le paiement initial est introuvable."); return json({ ok: false, error: "PAYMENT_INTENT_MISSING" }, 409); }
    await appendEvent(client, s, "pricing_finalized", "pricing_finalized", `pricing_finalized:${s.id}:${returnState}:${finalCents}`, { returnState, finalAmountCents: finalCents, pricingSnapshot: p }, finalCents / 100);
    await client.from("rental_sessions").update({ final_amount_cents: finalCents }).eq("id", s.id);
    const stripe = new Stripe(secret, { apiVersion: STRIPE_API_VERSION, httpClient: Stripe.createFetchHttpClient() }); let intent = await stripe.paymentIntents.retrieve(pi); const method = await paymentMethodType(stripe, intent), strat = strategy(s, intent, method), capturedBefore = Math.max(cents(s.captured_amount_cents), cents(intent.amount_received)), refundedBefore = cents(s.refunded_amount_cents), savedCustomer = String(s.stripe_customer_id ?? ""), savedPaymentMethod = String(s.stripe_payment_method_id ?? ""), maximumStripeDueWithoutSavedMethod = strat === "manual_capture" ? cents(intent.amount_capturable) : capturedBefore, minimumCreditCents = (!savedCustomer || !savedPaymentMethod) ? Math.max(0, finalCents - maximumStripeDueWithoutSavedMethod) : 0, reservation = await reserveMembershipRentalCredit(client, String(s.id), finalCents, minimumCreditCents); if (!reservation.requirementMet) { const fallback = plan(strat, finalCents, deposit, cents(intent.amount_capturable), capturedBefore, refundedBefore); await client.from("rental_sessions").update({ settlement_status: "supplemental_required", settlement_error: "SAVED_PAYMENT_METHOD_MISSING", state: "needs_support", supplemental_amount_cents: fallback.supplemental, settlement_locked_at: null }).eq("id", s.id); return json({ ok: false, requires_action: true, error: "SUPPLEMENTAL_PAYMENT_REQUIRED", supplemental_cents: fallback.supplemental }, 409); } membershipCreditReservedCents = reservation.reserved; const stripeAmountDueCents = stripeAmountAfterMembershipCredit(finalCents, membershipCreditReservedCents), steps = plan(strat, stripeAmountDueCents, deposit, cents(intent.amount_capturable), capturedBefore, refundedBefore); let captured = capturedBefore, refunded = refundedBefore, canceled = false, supplementalPI = String(s.stripe_supplemental_payment_intent_id ?? "") || null, supplementalCaptured = 0;
    if (steps.cancel && intent.status === "requires_capture") { stripeSideEffectStarted = true; intent = await stripe.paymentIntents.cancel(pi, {}, { idempotencyKey: `settlement_cancel_${s.id}` }); canceled = true; }
    if (steps.capture > 0 && intent.status === "requires_capture") {
      try { stripeSideEffectStarted = true; intent = await stripe.paymentIntents.capture(pi, { amount_to_capture: steps.capture, amount_details: amountDetails(steps.capture) } as any, { idempotencyKey: `settlement_capture_v3_${s.id}_${steps.capture}` }); }
      catch (error) { const c = errorCode(error); await markMembershipCreditForReconciliation(client, String(s.id)); await logApi(client, { service: "stripe", endpoint: "payment_intents.capture", method: "POST", status_code: 502, request: { rentalSessionId: s.id, amount_cents: steps.capture, line_items_total_cents: steps.capture }, response: null, error: c }); await fail(client, s, c, "La capture du montant final Stripe a échoué et doit être réconciliée.", { provider: cleanError(error), operation: "capture", intent_status: intent.status, amount_capturable_cents: intent.amount_capturable, card_capture_method: cardCapture(intent), top_level_capture_method: intent.capture_method, stripe_api_version: "2025-09-30.clover" }); return json({ ok: false, error: c }, 502); }
      captured = cents(intent.amount_received || steps.capture); await client.from("rental_sessions").update({ captured_amount_cents: captured }).eq("id", s.id); await logApi(client, { service: "stripe", endpoint: "payment_intents.capture", method: "POST", status_code: 200, request: { rentalSessionId: s.id, amount_cents: steps.capture, line_items_total_cents: steps.capture }, response: { id: intent.id, status: intent.status, amount_received: intent.amount_received, amount_capturable: intent.amount_capturable }, error: null });
    }
    if (steps.refund > 0) { stripeSideEffectStarted = true; const r = await stripe.refunds.create({ payment_intent: pi, amount: steps.refund }, { idempotencyKey: `settlement_refund_${s.id}_${steps.refund}` }); refunded += steps.refund; await client.from("rental_sessions").update({ refunded_amount_cents: refunded }).eq("id", s.id); await logApi(client, { service: "stripe", endpoint: "refunds.create", method: "POST", status_code: 200, request: { rentalSessionId: s.id, amount_cents: steps.refund }, response: { id: r.id, status: r.status }, error: null }); }
    if (steps.supplemental > 0) { const customer = String(s.stripe_customer_id ?? ""), pm = String(s.stripe_payment_method_id ?? ""); if (!customer || !pm) { if (!stripeSideEffectStarted) { await reverseMembershipRentalCredit(client, String(s.id), "saved_payment_method_missing_before_stripe_side_effect"); membershipCreditReservedCents = 0; } else await markMembershipCreditForReconciliation(client, String(s.id)); await client.from("rental_sessions").update({ settlement_status: "supplemental_required", settlement_error: "SAVED_PAYMENT_METHOD_MISSING", state: "needs_support", supplemental_amount_cents: steps.supplemental, settlement_locked_at: null }).eq("id", s.id); return json({ ok: false, requires_action: true, error: "SUPPLEMENTAL_PAYMENT_REQUIRED", supplemental_cents: steps.supplemental }, 409); } stripeSideEffectStarted = true; const sp = await stripe.paymentIntents.create({ amount: steps.supplemental, currency: String(s.currency ?? "CHF").toLowerCase(), customer, payment_method: pm, off_session: true, confirm: true, description: "Chargeurs.ch — complément de location", metadata: { rental_session_id: String(s.id) } }, { idempotencyKey: `settlement_supplemental_${s.id}_${steps.supplemental}` }); supplementalPI = sp.id; if (sp.status !== "succeeded") { await markMembershipCreditForReconciliation(client, String(s.id)); await client.from("rental_sessions").update({ settlement_status: "supplemental_required", settlement_error: "SUPPLEMENTAL_COLLECTION_FAILED", state: "needs_support", supplemental_amount_cents: steps.supplemental, stripe_supplemental_payment_intent_id: supplementalPI, settlement_locked_at: null }).eq("id", s.id); return json({ ok: false, requires_action: true, error: "SUPPLEMENTAL_COLLECTION_FAILED" }, 409); } supplementalCaptured = cents(sp.amount_received || steps.supplemental); }
    const totalCaptured = captured + supplementalCaptured; const membershipCreditCommittedCents = await commitMembershipRentalCredit(client, String(s.id), finalCents); if (membershipCreditCommittedCents > membershipCreditReservedCents || membershipCreditCommittedCents > finalCents) throw new Error("MEMBERSHIP_CREDIT_COMMIT_MISMATCH"); membershipCreditCommitted = true;
    const refundedPath = refunded > 0 || canceled; const current = await orchState(client, String(s.id)); if (current?.state === "pricing_finalized") await appendEvent(client, s, refundedPath ? "payment_refunded" : "payment_captured", refundedPath ? "refunded" : "payment_captured", refundedPath ? `payment_refunded:settlement:${s.id}:${refunded}:${canceled}` : `payment_captured:settlement:${s.id}:${totalCaptured}`, { returnState, strategy: strat, capturedCents: totalCaptured, refundedCents: refunded, supplementalCents: steps.supplemental, membershipCreditAppliedCents: membershipCreditCommittedCents, canceledAuthorization: canceled }, finalCents / 100);
    const stripeNetPaid = Math.max(0, totalCaptured - refunded); const totalPaid = stripeNetPaid + membershipCreditCommittedCents; const after = await orchState(client, String(s.id)); if (after?.state !== "completed") await appendEvent(client, s, "rental_completed", "completed", `rental_completed:settlement:${s.id}:${finalCents}`, { returnState, strategy: strat, netPaidCents: totalPaid, stripeNetPaidCents: stripeNetPaid, membershipCreditAppliedCents: membershipCreditCommittedCents }, finalCents / 100);
    const completedAt = new Date().toISOString(); await client.from("payments").update({ status: refunded > 0 ? (refunded >= totalCaptured ? "refunded" : "partially_refunded") : canceled ? "canceled" : "succeeded", settlement_strategy: strat, amount_captured_cents: totalCaptured, amount_refunded_cents: refunded }).eq("rental_session_id", s.id); await client.from("rental_sessions").update({ final_amount_cents: finalCents, amount: finalCents / 100, amount_paid: totalPaid / 100, captured_amount_cents: totalCaptured, refunded_amount_cents: refunded, supplemental_amount_cents: steps.supplemental, stripe_supplemental_payment_intent_id: supplementalPI, settlement_strategy: strat, settlement_status: "settled", settlement_error: null, settlement_locked_at: null, settled_at: completedAt, state: "completed", closed_at: completedAt, failure_code: null, failure_message: null }).eq("id", s.id); await audit(client, "settlement.completed", String(s.id), { final_amount_cents: finalCents, captured_amount_cents: totalCaptured, refunded_amount_cents: refunded, membership_credit_applied_cents: membershipCreditCommittedCents, strategy: strat, stripe_api_version: "2025-09-30.clover" });
    return json({ ok: true, settlement_status: "settled", strategy: strat, final_amount_cents: finalCents, captured_amount_cents: totalCaptured, refunded_amount_cents: refunded, membership_credit_applied_cents: membershipCreditCommittedCents, supplemental_amount_cents: steps.supplemental });
  } catch (error) { const c = errorCode(error); if (rentalId) try { if (shouldReverseMembershipCreditReservation({ reservedCreditCents: membershipCreditReservedCents, stripeSideEffectStarted, creditCommitted: membershipCreditCommitted })) await reverseMembershipRentalCredit(client, rentalId, "settlement_failed_before_stripe_side_effect"); else if (membershipCreditReservedCents > 0 && !membershipCreditCommitted) await markMembershipCreditForReconciliation(client, rentalId); const { data: s } = await client.from("rental_sessions").select("*").eq("id", rentalId).maybeSingle(); if (s) await fail(client, s, "SETTLEMENT_INTERNAL_ERROR", "Le règlement final a échoué et doit être réconcilié.", { underlying_code: c, provider: cleanError(error), stripe_api_version: "2025-09-30.clover" }); } catch {} return json({ ok: false, error: "SETTLEMENT_INTERNAL_ERROR" }, 500); }
});
