-- OBSOLÈTE — NE PAS EXÉCUTER.
--
-- Ce fichier était le bootstrap manuel antérieur aux migrations versionnées.
-- Son contenu historique reste disponible dans Git, mais il accordait des
-- droits d'écriture directs à `authenticated` et stockait l'adresse IP brute.
--
-- Utiliser exclusivement, dans l'ordre, les migrations rejouables :
--
--   supabase/migrations/20260719133000_platform_api_readonly_v1.sql
--   supabase/migrations/20260719143000_platform_api_legacy_reconciliation.sql
--
-- La seconde migration sécurise également une base staging sur laquelle
-- l'ancienne version de ce fichier aurait déjà été exécutée. Procédure :
--
--   docs/PLATFORM_API_STAGING.md
