// Kiosk payment launcher. It returns a Chargeurs-hosted mobile payment portal.
// The phone, never the kiosk, selects card-hold versus TWINT prepaid semantics.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
const headers={...corsHeaders,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-kiosk-token, x-idempotency-key","Access-Control-Expose-Headers":"x-correlation-id"};
const admin=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
async function sha256(input:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(req:Request,d:any,stationId:string){const token=(req.headers.get("X-Kiosk-Token")??"").trim();if(token.length<24)return null;const hash=await sha256(token);const{data}=await d.from("kiosk_devices").select("id,station_id,active,token_revoked,token_expires_at").eq("token_hash",hash).maybeSingle();if(!data||data.station_id!==stationId||!data.active||data.token_revoked)return null;if(data.token_expires_at&&Date.parse(data.token_expires_at)<Date.now())return null;return data;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers});const cid=crypto.randomUUID(),json=(body:Record<string,unknown>,status=200)=>new Response(JSON.stringify({...body,correlationId:cid}),{status,headers:{...headers,"Content-Type":"application/json","X-Correlation-Id":cid}});if(req.method!=="POST")return json({ok:false,error:"METHOD_NOT_ALLOWED"},405);try{const body=await req.json().catch(()=>({})),id=typeof body.rentalSessionId==="string"?body.rentalSessionId:"";if(!id)return json({ok:false,error:"MISSING_SESSION"},400);const d=admin(),{data:s,error}=await d.from("rental_sessions").select("id,station_id,kiosk_device_id,public_session_code,customer_language,expires_at,pricing_snapshot,deposit_amount_cents,paid_at").eq("id",id).maybeSingle();if(error)throw error;if(!s)return json({ok:false,error:"SESSION_NOT_FOUND"},404);const device=await auth(req,d,String(s.station_id??""));if(!device)return json({ok:false,error:"KIOSK_AUTH_INVALID"},401);if(String(s.kiosk_device_id??"")!==String(device.id))return json({ok:false,error:"KIOSK_DEVICE_MISMATCH"},403);if(s.expires_at&&Date.parse(s.expires_at)<Date.now())return json({ok:false,error:"SESSION_EXPIRED"},410);if(s.paid_at)return json({ok:false,error:"SESSION_ALREADY_PAID"},409);const lang=s.customer_language==="de"||s.customer_language==="en"?s.customer_language:"fr",base=(Deno.env.get("SUPABASE_URL")??"").replace(/\/$/,"");if(!base)return json({ok:false,error:"SUPABASE_URL_NOT_CONFIGURED"},503);const expires=s.expires_at??new Date(Date.now()+20*60_000).toISOString(),launch=`${base}/functions/v1/payment-portal?rental=${encodeURIComponent(String(s.id))}&c=${encodeURIComponent(String(s.public_session_code??""))}&lang=${lang}&view=choose`;await d.from("rental_sessions").update({checkout_url:launch,checkout_url_expires_at:expires,updated_at:new Date().toISOString()}).eq("id",s.id);return json({ok:true,checkout_url:launch,public_session_code:s.public_session_code,expires_at:expires,status:"awaiting_payment_choice",deposit_cents:Number(s.deposit_amount_cents??(s.pricing_snapshot as any)?.deposit_cents??0)});}catch(e){console.error("create-stripe-checkout launcher",e instanceof Error?e.message:"UNKNOWN");return json({ok:false,error:"PAYMENT_LAUNCH_FAILED"},500);}});
