create table if not exists public.advertising_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  status text not null default 'draft' check (status in ('draft','scheduled','active','paused','archived')),
  display_modes text[] not null default array['split','screensaver']::text[],
  all_stations boolean not null default true,
  starts_at timestamptz null,
  ends_at timestamptz null,
  idle_after_seconds integer not null default 45 check (idle_after_seconds between 10 and 900),
  split_ratio numeric(4,3) not null default 0.350 check (split_ratio between 0.20 and 0.50),
  priority integer not null default 100 check (priority between 0 and 10000),
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint advertising_campaigns_modes_valid check (
    cardinality(display_modes) > 0
    and display_modes <@ array['split','screensaver']::text[]
  ),
  constraint advertising_campaigns_dates_valid check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create table if not exists public.advertising_assets (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 160),
  storage_path text not null unique,
  media_type text not null check (media_type in ('image','video')),
  mime_type text not null,
  file_size_bytes bigint null check (file_size_bytes is null or file_size_bytes >= 0),
  width integer null check (width is null or width > 0),
  height integer null check (height is null or height > 0),
  duration_seconds numeric(8,3) null check (duration_seconds is null or duration_seconds > 0),
  poster_storage_path text null,
  active boolean not null default true,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.advertising_campaign_items (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.advertising_campaigns(id) on delete cascade,
  asset_id uuid not null references public.advertising_assets(id) on delete restrict,
  sort_order integer not null default 0 check (sort_order >= 0),
  image_duration_seconds integer null check (image_duration_seconds is null or image_duration_seconds between 2 and 300),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, asset_id)
);

create table if not exists public.advertising_campaign_stations (
  campaign_id uuid not null references public.advertising_campaigns(id) on delete cascade,
  station_id text not null references public.stations(station_id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (campaign_id, station_id)
);

create table if not exists public.advertising_impressions (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.advertising_campaigns(id) on delete cascade,
  asset_id uuid not null references public.advertising_assets(id) on delete cascade,
  station_id text not null references public.stations(station_id) on update cascade on delete cascade,
  kiosk_device_id uuid null references public.kiosk_devices(id) on delete set null,
  display_mode text not null check (display_mode in ('split','screensaver')),
  started_at timestamptz not null default now(),
  completed_at timestamptz null,
  duration_ms integer null check (duration_ms is null or duration_ms >= 0),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists advertising_campaigns_status_window_idx on public.advertising_campaigns(status, starts_at, ends_at, priority desc);
create index if not exists advertising_campaign_items_campaign_order_idx on public.advertising_campaign_items(campaign_id, enabled, sort_order);
create index if not exists advertising_campaign_stations_station_idx on public.advertising_campaign_stations(station_id, campaign_id);
create index if not exists advertising_impressions_station_started_idx on public.advertising_impressions(station_id, started_at desc);
create index if not exists advertising_impressions_campaign_started_idx on public.advertising_impressions(campaign_id, started_at desc);

alter table public.advertising_campaigns enable row level security;
alter table public.advertising_assets enable row level security;
alter table public.advertising_campaign_items enable row level security;
alter table public.advertising_campaign_stations enable row level security;
alter table public.advertising_impressions enable row level security;

revoke all on public.advertising_campaigns from anon, authenticated;
revoke all on public.advertising_assets from anon, authenticated;
revoke all on public.advertising_campaign_items from anon, authenticated;
revoke all on public.advertising_campaign_stations from anon, authenticated;
revoke all on public.advertising_impressions from anon, authenticated;

grant all on public.advertising_campaigns to service_role;
grant all on public.advertising_assets to service_role;
grant all on public.advertising_campaign_items to service_role;
grant all on public.advertising_campaign_stations to service_role;
grant all on public.advertising_impressions to service_role;
grant usage, select on sequence public.advertising_impressions_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'advertising-media',
  'advertising-media',
  true,
  104857600,
  array['image/jpeg','image/png','image/webp','video/mp4','video/webm']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
