-- Hidden kiosk operator access. The fixed operator PIN is never stored in
-- plaintext in the repository or in the Android/Web bundles. This table keeps
-- only a bcrypt digest; successful verification grants no backend role or
-- bearer token and is used solely to open local native maintenance UI.

create table if not exists public.kiosk_operator_access_policy (
  id smallint primary key check (id = 1),
  pin_hash text not null check (pin_hash ~ '^\$2[aby]\$[0-9]{2}\$'),
  updated_at timestamptz not null default now()
);

alter table public.kiosk_operator_access_policy enable row level security;
revoke all on table public.kiosk_operator_access_policy from public, anon, authenticated;

create table if not exists public.kiosk_operator_access_attempts (
  id bigint generated by default as identity primary key,
  source_hash text not null check (source_hash ~ '^[0-9a-f]{64}$'),
  device_public_id uuid,
  outcome text not null check (outcome in ('accepted', 'rejected', 'rate_limited')),
  created_at timestamptz not null default now()
);

alter table public.kiosk_operator_access_attempts enable row level security;
revoke all on table public.kiosk_operator_access_attempts from public, anon, authenticated;

create index if not exists kiosk_operator_access_attempts_source_recent_idx
  on public.kiosk_operator_access_attempts(source_hash, created_at desc);
create index if not exists kiosk_operator_access_attempts_device_recent_idx
  on public.kiosk_operator_access_attempts(device_public_id, created_at desc)
  where device_public_id is not null;

-- bcrypt cost 12 digest for the owner-selected operator PIN. The plaintext PIN
-- is intentionally absent from this migration.
insert into public.kiosk_operator_access_policy(id, pin_hash, updated_at)
values (1, '$2a$12$pdI1ta6YDAuUVGvRsD0dPeT1aCpIL2GEvTyhOUuXvQ5oJ9B/tOLSC', now())
on conflict (id) do update
set pin_hash = excluded.pin_hash,
    updated_at = excluded.updated_at;

create or replace function public.verify_kiosk_operator_pin(
  p_pin text,
  p_source_hash text,
  p_device_public_id uuid
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  v_pin_hash text;
  v_recent_source integer := 0;
  v_recent_device integer := 0;
  v_recent integer := 0;
  v_last_failure timestamptz;
  v_delay_seconds integer := 0;
begin
  if p_pin is null or p_pin !~ '^\d{6}$'
     or p_source_hash is null or p_source_hash !~ '^[0-9a-f]{64}$'
     or p_device_public_id is null then
    return jsonb_build_object('ok', false, 'error', 'INVALID_OPERATOR_REQUEST');
  end if;

  select count(*) into v_recent_source
  from public.kiosk_operator_access_attempts
  where source_hash = p_source_hash
    and outcome in ('rejected', 'rate_limited')
    and created_at > now() - interval '10 minutes';

  select count(*) into v_recent_device
  from public.kiosk_operator_access_attempts
  where device_public_id = p_device_public_id
    and outcome in ('rejected', 'rate_limited')
    and created_at > now() - interval '10 minutes';

  select max(created_at) into v_last_failure
  from public.kiosk_operator_access_attempts
  where (source_hash = p_source_hash or device_public_id = p_device_public_id)
    and outcome in ('rejected', 'rate_limited')
    and created_at > now() - interval '10 minutes';

  v_recent := greatest(v_recent_source, v_recent_device);
  v_delay_seconds := case least(v_recent, 4)
    when 0 then 0
    when 1 then 2
    when 2 then 5
    when 3 then 15
    else 60
  end;

  if v_recent_source >= 5 or v_recent_device >= 5
     or (v_delay_seconds > 0 and v_last_failure > now() - make_interval(secs => v_delay_seconds)) then
    insert into public.kiosk_operator_access_attempts(source_hash, device_public_id, outcome)
    values (p_source_hash, p_device_public_id, 'rate_limited');
    return jsonb_build_object('ok', false, 'error', 'TOO_MANY_OPERATOR_ATTEMPTS');
  end if;

  select pin_hash into v_pin_hash
  from public.kiosk_operator_access_policy
  where id = 1;

  if v_pin_hash is null or extensions.crypt(p_pin, v_pin_hash) <> v_pin_hash then
    insert into public.kiosk_operator_access_attempts(source_hash, device_public_id, outcome)
    values (p_source_hash, p_device_public_id, 'rejected');
    return jsonb_build_object('ok', false, 'error', 'INVALID_OPERATOR_PIN');
  end if;

  insert into public.kiosk_operator_access_attempts(source_hash, device_public_id, outcome)
  values (p_source_hash, p_device_public_id, 'accepted');

  return jsonb_build_object('ok', true);
end;
$function$;

revoke all on function public.verify_kiosk_operator_pin(text, text, uuid) from public, anon, authenticated;
grant execute on function public.verify_kiosk_operator_pin(text, text, uuid) to service_role;
