// This file is automatically generated. Keep custom transport changes minimal.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { kioskAwareFetch } from '@/lib/kioskFetch';

// Vercel previously served a blank page when the reused frontend project did
// not expose the Chargeurs.ch VITE_* variables to a deployment. These are
// public browser credentials (never service-role secrets) for the staging
// project, so the staging build has a fail-safe public fallback while the
// Vercel project is being repurposed for Chargeurs.ch.
const STAGING_SUPABASE_URL = 'https://xqepbqnaenoeyfjkjnzl.supabase.co';
const STAGING_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_39LXZ2QrezT20u9dqDQX2Q_-yq4GX0d';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || STAGING_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || STAGING_SUPABASE_PUBLISHABLE_KEY;
const isPasswordRecoveryRoute = /\/(?:admin|compte)\/reset-password$/.test(window.location.pathname);
const isAccountSurface = () => window.location.pathname === '/compte' || window.location.pathname.startsWith('/compte/');

// Keep customer Chargeurs+ authentication isolated from back-office/admin auth.
// Both clients use the same Supabase project and RLS, but persist independent
// sessions so an admin can remain signed in while testing/using Chargeurs+.
const adminSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Account routes own their auth callback through the dedicated customer
    // client below; the admin/default client must not consume those tokens.
    detectSessionInUrl: !isPasswordRecoveryRoute && !isAccountSurface(),
    flowType: 'pkce',
  },
  global: {
    // The kiosk token is injected only for the station-bound cabinet sync
    // function. It is never added to database, auth, Stripe or other requests.
    fetch: kioskAwareFetch,
  },
});

export const customerSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: 'chargeurs-plus-auth',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !isPasswordRecoveryRoute && isAccountSurface(),
    flowType: 'pkce',
  },
  global: { fetch: kioskAwareFetch },
});

// Existing application code imports `supabase`. Route that facade dynamically
// so /compte/* always uses the isolated Chargeurs+ session while kiosk/admin/
// public surfaces retain the long-standing default session. The proxy keeps
// route changes inside the SPA safe without forcing a page reload.
export const supabase = new Proxy(adminSupabase, {
  get(_target, property) {
    const client = isAccountSurface() ? customerSupabase : adminSupabase;
    const value = Reflect.get(client, property, client);
    return typeof value === 'function' ? value.bind(client) : value;
  },
}) as typeof adminSupabase;

/**
 * Password-recovery emails must work when opened from Gmail, Safari or a
 * different device than the one that requested them. A PKCE verifier is local
 * to the requesting browser, so it is unsuitable for that specific hand-off.
 *
 * This client is used only to request and complete password recovery. Recovery
 * tokens stay in the URL fragment, are cleared immediately after setSession,
 * are never persisted and are signed out locally after the password changes.
 */
export const passwordRecoveryAuth = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    flowType: 'implicit',
  },
  global: { fetch: kioskAwareFetch },
});
