// This file is automatically generated. Keep custom transport changes minimal.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { kioskAwareFetch } from '@/lib/kioskFetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    // The kiosk token is injected only for the station-bound cabinet sync
    // function. It is never added to database, auth, Stripe or other requests.
    fetch: kioskAwareFetch,
  },
});
